version: '3.8'
services:
  portfolio:
    image: botflook/portfolio:latest
    container_name: portfolio-app
    ports:
      - "80:80"  # เปลี่ยนเป็น port 80 เพื่อให้ Nginx reverse proxy ได้
    restart: unless-stopped